name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Backend
        working-directory: ./server
        run: |
          mvn clean install

      - name: Build Frontend
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Build Backend Docker Image
        run: |
          docker build -t examdevops-server-1 ./server

      - name: Build Frontend Docker Image
        run: |
          docker build -t examdevops-client-1 ./client

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image
        run: |
          docker tag examdevops-server-1 ${{ secrets.DOCKER_USERNAME }}/examdevops-server-1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/examdevops-server-1:latest

      - name: Push Frontend Image
        run: |
          docker tag examdevops-client-1 ${{ secrets.DOCKER_USERNAME }}/examdevops-client-1:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/examdevops-client-1:latest

